#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginGG.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name= "SiteSqlServer")]
	public partial class HnueDangKyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHnueDangKyThi(HnueDangKyThi instance);
    partial void UpdateHnueDangKyThi(HnueDangKyThi instance);
    partial void DeleteHnueDangKyThi(HnueDangKyThi instance);
        #endregion

        public HnueDangKyDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public HnueDangKyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HnueDangKyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HnueDangKyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HnueDangKyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HnueDangKyThi> HnueDangKyThis
		{
			get
			{
				return this.GetTable<HnueDangKyThi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HnueDangKyThi")]
	public partial class HnueDangKyThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _EmailUser;
		
		private string _ho_ten;
		
		private string _ten_theonn;
		
		private string _ngay_sinh;
		
		private string _loai_giay_to;
		
		private string _gioi_tinh;
		
		private string _cccd;
		
		private string _email;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private string _dot_thi;
		
		private string _so_nam_hoc_nn;
		
		private string _file_cccd_truoc_url;
		
		private string _file_cccd_sau_url;
		
		private string _file_anh_the_url;
		
		private string _file_bienlai_noptien_url;
		
		private string _hinh_thuc_thi;
		
		private string _trang_thai;
		
		private System.Nullable<System.DateTime> _ngay_dang_ky;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnEmailUserChanging(string value);
    partial void OnEmailUserChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onten_theonnChanging(string value);
    partial void Onten_theonnChanged();
    partial void Onngay_sinhChanging(string value);
    partial void Onngay_sinhChanged();
    partial void Onloai_giay_toChanging(string value);
    partial void Onloai_giay_toChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Ondot_thiChanging(string value);
    partial void Ondot_thiChanged();
    partial void Onso_nam_hoc_nnChanging(string value);
    partial void Onso_nam_hoc_nnChanged();
    partial void Onfile_cccd_truoc_urlChanging(string value);
    partial void Onfile_cccd_truoc_urlChanged();
    partial void Onfile_cccd_sau_urlChanging(string value);
    partial void Onfile_cccd_sau_urlChanged();
    partial void Onfile_anh_the_urlChanging(string value);
    partial void Onfile_anh_the_urlChanged();
    partial void Onfile_bienlai_noptien_urlChanging(string value);
    partial void Onfile_bienlai_noptien_urlChanged();
    partial void Onhinh_thuc_thiChanging(string value);
    partial void Onhinh_thuc_thiChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_dang_kyChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_dang_kyChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public HnueDangKyThi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUser", DbType="NVarChar(255)")]
		public string EmailUser
		{
			get
			{
				return this._EmailUser;
			}
			set
			{
				if ((this._EmailUser != value))
				{
					this.OnEmailUserChanging(value);
					this.SendPropertyChanging();
					this._EmailUser = value;
					this.SendPropertyChanged("EmailUser");
					this.OnEmailUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_theonn", DbType="NVarChar(255)")]
		public string ten_theonn
		{
			get
			{
				return this._ten_theonn;
			}
			set
			{
				if ((this._ten_theonn != value))
				{
					this.Onten_theonnChanging(value);
					this.SendPropertyChanging();
					this._ten_theonn = value;
					this.SendPropertyChanged("ten_theonn");
					this.Onten_theonnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_giay_to", DbType="NVarChar(100)")]
		public string loai_giay_to
		{
			get
			{
				return this._loai_giay_to;
			}
			set
			{
				if ((this._loai_giay_to != value))
				{
					this.Onloai_giay_toChanging(value);
					this.SendPropertyChanging();
					this._loai_giay_to = value;
					this.SendPropertyChanged("loai_giay_to");
					this.Onloai_giay_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(10)")]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dot_thi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dot_thi
		{
			get
			{
				return this._dot_thi;
			}
			set
			{
				if ((this._dot_thi != value))
				{
					this.Ondot_thiChanging(value);
					this.SendPropertyChanging();
					this._dot_thi = value;
					this.SendPropertyChanged("dot_thi");
					this.Ondot_thiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_nam_hoc_nn", DbType="NVarChar(100)")]
		public string so_nam_hoc_nn
		{
			get
			{
				return this._so_nam_hoc_nn;
			}
			set
			{
				if ((this._so_nam_hoc_nn != value))
				{
					this.Onso_nam_hoc_nnChanging(value);
					this.SendPropertyChanging();
					this._so_nam_hoc_nn = value;
					this.SendPropertyChanged("so_nam_hoc_nn");
					this.Onso_nam_hoc_nnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_cccd_truoc_url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string file_cccd_truoc_url
		{
			get
			{
				return this._file_cccd_truoc_url;
			}
			set
			{
				if ((this._file_cccd_truoc_url != value))
				{
					this.Onfile_cccd_truoc_urlChanging(value);
					this.SendPropertyChanging();
					this._file_cccd_truoc_url = value;
					this.SendPropertyChanged("file_cccd_truoc_url");
					this.Onfile_cccd_truoc_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_cccd_sau_url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string file_cccd_sau_url
		{
			get
			{
				return this._file_cccd_sau_url;
			}
			set
			{
				if ((this._file_cccd_sau_url != value))
				{
					this.Onfile_cccd_sau_urlChanging(value);
					this.SendPropertyChanging();
					this._file_cccd_sau_url = value;
					this.SendPropertyChanged("file_cccd_sau_url");
					this.Onfile_cccd_sau_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_anh_the_url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string file_anh_the_url
		{
			get
			{
				return this._file_anh_the_url;
			}
			set
			{
				if ((this._file_anh_the_url != value))
				{
					this.Onfile_anh_the_urlChanging(value);
					this.SendPropertyChanging();
					this._file_anh_the_url = value;
					this.SendPropertyChanged("file_anh_the_url");
					this.Onfile_anh_the_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_bienlai_noptien_url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string file_bienlai_noptien_url
		{
			get
			{
				return this._file_bienlai_noptien_url;
			}
			set
			{
				if ((this._file_bienlai_noptien_url != value))
				{
					this.Onfile_bienlai_noptien_urlChanging(value);
					this.SendPropertyChanging();
					this._file_bienlai_noptien_url = value;
					this.SendPropertyChanged("file_bienlai_noptien_url");
					this.Onfile_bienlai_noptien_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thuc_thi", DbType="NVarChar(50)")]
		public string hinh_thuc_thi
		{
			get
			{
				return this._hinh_thuc_thi;
			}
			set
			{
				if ((this._hinh_thuc_thi != value))
				{
					this.Onhinh_thuc_thiChanging(value);
					this.SendPropertyChanging();
					this._hinh_thuc_thi = value;
					this.SendPropertyChanged("hinh_thuc_thi");
					this.Onhinh_thuc_thiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dang_ky", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dang_ky
		{
			get
			{
				return this._ngay_dang_ky;
			}
			set
			{
				if ((this._ngay_dang_ky != value))
				{
					this.Onngay_dang_kyChanging(value);
					this.SendPropertyChanging();
					this._ngay_dang_ky = value;
					this.SendPropertyChanged("ngay_dang_ky");
					this.Onngay_dang_kyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
