<?xml version="1.0" encoding="utf-8"?><Database Name="dnnregrister" Class="HnueEmailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.HnueEmail" Member="HnueEmails">
    <Type Name="HnueEmail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Accesstoken" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreateAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>